apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: newrolebinding
  namespace: ns1
subjects:
  - kind: User
    name: "roopa"  
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role1  
  apiGroup: rbac.authorization.k8s.io
